language: ruby
rvm:
  - 1.9.3
before_install:
  - git submodule update --init --recursive
before_script:
  - sudo apt-get install nmap
  - export APP_ROOT=$(dirname $0)
  - export SSLYZE_PATH="$APP_ROOT/vendor/sslyze/sslyze.py"
  - export SQLMAP_PATH="$APP_ROOT/vendor/sslyze/sqlmap.py"