language: ruby
rvm:
  - 2.1.10
  - 2.2.9
  - 2.3.6
before_install:
  - git submodule update --init --recursive --force
  - gem update bundler
before_script:
  #- go get github.com/FiloSottile/Heartbleed
  #- go install github.com/FiloSottile/Heartbleed
  #- which Heartbleed
  - sudo apt-get update
  - sudo apt-get install build-essential git libxml2 libxml2-dev
    libxslt-dev libcurl4-openssl-dev libsqlite3-dev libyaml-dev zlib1g-dev
    python-dev python-pip python-setuptools curl nmap w3af-console wget golang
  - export SSLYZE_PATH="/home/travis/build/gauntlt/gauntlt/vendor/sslyze/sslyze_cli.py"
  - export SQLMAP_PATH="/home/travis/build/gauntlt/gauntlt/vendor/sqlmap/sqlmap.py"
  - 'cd vendor/Garmr && sudo python setup.py install && cd ../..'
  - 'cd vendor && tar xvfz dirb222.tar.gz && chmod -R 755 ./dirb222 && cd ./dirb222 && ./configure && make && sudo cp dirb /usr/local/bin/ && cd ..'
  - export DIRB_WORDLISTS="/home/travis/build/gauntlt/gauntlt/vendor/dirb/wordlists"
  - 'wget https://github.com/Arachni/arachni/releases/download/v1.5.1/arachni-1.5.1-0.5.12-linux-x86_64.tar.gz && tar xzvf arachni-1.5.1-0.5.12-linux-x86_64.tar.gz > /dev/null && sudo cp ./arachni-1.5.1-0.5.12/bin/* /usr/local/bin/'
notifications:
  slack: gauntlt:UEjUro5MQLFO1DwuETgUxb7u
