language: ruby
rvm:
  - 1.9.3
  - jruby-head
before_install:
  - git submodule update --init --recursive
before_script:
  - sudo apt-get install nmap
  - export SSLYZE_PATH="/home/travis/build/gauntlt/gauntlt/vendor/sslyze/sslyze.py"
  - export SQLMAP_PATH="/home/travis/build/gauntlt/gauntlt/vendor/sqlmap/sqlmap.py"
  - 'cd vendor/Garmr && sudo python setup.py install && cd ../..'
  - 'cd vendor && tar xvfz dirb203.tar.gz && cd dirb && ./configure && make && cp dirb /usr/local/bin/ && cd ..'
  - export DIRB_WORDLISTS="/home/travis/build/gauntlt/gauntlt/vendor/dirb/wordlists"

matrix:
  allow_failures:
    - rvm: jruby-head
