language: ruby
rvm:
  - 1.9.3
before_install:
  - git submodule update --init --recursive
before_script:
  - sudo apt-get install nmap
  - export SSLYZE_PATH="/home/vagrant/builds/thegauntlet/gauntlt/vendor/sslyze/sslyze.py"
  - export SQLMAP_PATH="/home/vagrant/builds/thegauntlet/gauntlt/vendor/sslyze/sqlmap.py"